version: "3.9"

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.production
    depends_on:
      - aws

  aws:
    image: localstack/localstack:1.4
    environment:
      SERVICES: s3,sts,secretsmanager
